[package]
name = "pymemprofile_api"
version = "0.1.0"
authors = ["Itamar Turner-Trauring <itamar@pythonspeed.com>"]
edition = "2018"
license = "Apache 2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
im = "14.2.0"
libc = "0.2"
itertools = "0.8.2"
lazy_static = "1.4.0"
rustc-hash = "1.0.1"
ahash = "0.5.6"
parking_lot = "0.11.0"
derivative = "2.1.1"

[target.'cfg(target_os = "linux")'.dependencies.jemallocator]
version = "0.3.2"

[dependencies.inferno]
version = "0.9.9"
default-features = false

[dev-dependencies]
proptest = "0.9.5"

[lib]
name = "pymemprofile_api"
crate_type = ["staticlib"]